### ISSUE TITLE
When board is idle for long time, getting blank error page

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#1023]
Displays "Board not found. This board may be private" error when it is idle for long time.

**Comment by baskar383** [comment]
Sorry for the delayed response. Fixed in this commit 4276bad

**Comment by rrjanbiah** [comment]
@baskar383 Can you explain what was the cause and how above fix will work?

**Comment by baskar383** [comment]
we are fixed in 401 error for private boards. In board view page more than 10mins open continuously some time the access token expired 401 error through in for that board it will redirect to private board page. Now we fixed once the access token is expired then check the board is private board or not if not means they will send the refresh token it will works fine now.
