### ISSUE TITLE
Blank page when opening board after long time

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#1116]
401 (Authentication failed) error for every requests. Even getting same 401 for logout requests too (Previously, it wasn't the case). So, completely stuck with blank page. Had to clear cookies to restart.

**Comment by lmarikannan** [comment]
@rrjanbiah Sorry for the trouble. Actually this error occur due to refresh token and access token expiration time. Now we have fixed this on 2 files.

Need to replace the r.php file on `/server/php/R/r.php` path with this file [r.txt](https://github.com/RestyaPlatform/board/files/849781/r.txt) and change the file format `.txt` to `.php`.

And also replace the bootstrap.php file on `/server/php/boostrap.php` path with thie file [bootstrap.txt](https://github.com/RestyaPlatform/board/files/849786/bootstrap.txt) and change the file format  `.txt` to `.php`. It'll works.
