### ISSUE TITLE
In install script cron commands should be piped to /dev/null

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#1221]
This will avoid unnecessary mails from cron

**Comment by rrjanbiah** [comment]
Output could also be piped to a log file for debugging purpose

**Comment by lmarikannan** [comment]
Fixed on this commit - c0d4d34

**Comment by rrjanbiah** [comment]
The quotes are seems to be closed at wrong place. Need recheck

**Comment by lmarikannan** [comment]
This issue is fixed with below changes

1. https://github.com/RestyaPlatform/board/commit/c0d4d3452217020d5685445637b207fe873bcfd5#diff-e2930341cebfe21b6b1fd322a42667e2R544
2. https://github.com/RestyaPlatform/board/commit/c0d4d3452217020d5685445637b207fe873bcfd5#diff-e2930341cebfe21b6b1fd322a42667e2R1043

**Comment by rrjanbiah** [comment]
Please test it in real machine. Still quotes are looking not properly closed.

**Comment by lmarikannan** [comment]
Now this issue fixed on this commit https://github.com/RestyaPlatform/board/commit/a96bb73d42a7af3ae05c071f59c846cf64fec35b. And also tested in real machine.
