### ISSUE TITLE
Update failed

### ISSUE THREAD

**Issue by morphos88** [RestyaPlatform/board#1360]
## Expected Behavior
Update stop in sql script :
[restyaboard_install.log](https://github.com/RestyaPlatform/board/files/1348558/restyaboard_install.log)

I tried to restart but it stops at the same place.

**Comment by lmarikannan** [comment]
These SQL errors are raised because you have tried to update v0.5.2 second time. While running at first time, the fields are created in database. So at the second time, it shown errors as already exists. But it will not create any issue. Is there login issue raised after updating this like you have already mentioned in this comment https://github.com/RestyaPlatform/board/issues/1316#issuecomment-328761584?

**Comment by morphos88** [comment]
The problem is that the script does not finish and still waiting after "UPDATE 17"

**Comment by lmarikannan** [comment]
@morphos88 Oh. Can you please run this command manually `php /usr/share/nginx/html/restyaboard/server/php/upgrade_v0.5.1_v0.5.2.php` in SSH? And then try login?

**Comment by morphos88** [comment]
do nothing

**Comment by morphos88** [comment]
Ok script finish. I look in base and all timezone was set to null it's good ?

**Comment by morphos88** [comment]
Now i can't edit profil user and settings site

**Comment by lmarikannan** [comment]
@morphos88 

> Ok script finish. I look in base and all timezone was set to null it's good ?

Actually this script `upgrade_v0.5.1_v0.5.2.php` will update timezone in both users and settings table. So if it's null then the script not executed properly for you.

**Comment by morphos88** [comment]
Ok i roll back to 0.5.1. Can we solve problem ?

**Comment by morphos88** [comment]
Ok i execute sql script alone and comment script in batch.

I verify timezone in postgre and i update all timezone for settings and users

**Comment by lmarikannan** [comment]
@morphos88 Nice to hear. Closing this issue.
