### ISSUE TITLE
Internet explorer 11 - White space displaying in board page

### ISSUE THREAD

**Issue by lmarikannan** [RestyaPlatform/board#1376]
When I enter any of my boards in Internet Explorer, all I see is a white space. When I try the same in Chrome, I see all my lists properly.

IE version - Ver 11.1770.14393.0

**Comment by erl4nc** [comment]
I have users reporting similar issues.  On Windows 10 IE 11, a blank home page is served.  Any other browser (including Microsoft Edge) or even IE 11 on Windows 7 shows log in page.

**Comment by lmarikannan** [comment]
@erl4nc Actually login and boards listing page are working fine. But individual board view page is display as blank page. Can you please confirm the site is working in other browsers?

**Comment by erl4nc** [comment]
As I said, all other browsers work fine except IE 11 on Windows 10.  For my users, the home page is blank so they are unable to proceed.

**Comment by lmarikannan** [comment]
@erl4nc We need SSH or teamviewer access to understand more about your issue. Can you please contact through email info@restya.com?

**Comment by lmarikannan** [comment]
Fixed on this commit - https://github.com/RestyaPlatform/board/commit/d4420e14eb458100475e5cd79d2a44c3c197676b.

**Comment by erl4nc** [comment]
@lmarikannan, I tested the commit and it fixes the issue for most users.  There is still one user getting a blank login screen.  Unfortunately, I have very limited access to that machine nor can I provide access to it.  I suspect the browser is in compatibility mode.  When I test Restyaboard with IE 11 set in compatibility mode, the <form> is missing from login page.  Is this expected behavior?

**Comment by lmarikannan** [comment]
@erl4nc According to your statement, we have googled and find this link https://stackoverflow.com/questions/25077612/jquery-not-working-with-ie-11. You have to change the IE mode and then the site will work.
