### ISSUE TITLE
Install script fails due to redhat-lsb-core and psql in CentOS 7

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#1467]
From truecore:

I used your script on Centos 7, only modifications I did is Change DB Password 
1. script failed because redhat-lsb-core was not installed, should be checked in depencies
2. installed manually and re-run script - failed as psql could not startup - I had than to manually remove files and initdb
3. afterwards the script was running though.. but afterwards there was just a blank page /#/users/login => no login mask appeared
4. afterwards I decided to re-set VM and run manual setup... (I don't have the install log anymore...)

**Comment by kokeszko** [comment]
bug still exists. checked on latest patched CentOS 7.
1. missing package
2. failed to run postgresql service and initialize db
3. blank page after instalation

**Comment by sridhar391** [comment]
@kokeszko Can you please attach restyaboard_install.log file to analyze

**Comment by kitefishlabs** [comment]
I had a similar issue. Can start a new thread if it seems like a fresh issue.

Ubuntu 16.04 on Digital Ocean installing via ssh connection. I ran ssl certbot afterwards and that appears to be OK.


Ran the install 1 time, but it seemed to choke on a special char in the password I set. Changed the password. Ran install again, answered Y when asked if this was a fresh install.

[restyaboard_install.log.zip](https://github.com/RestyaPlatform/board/files/1749686/restyaboard_install.log.zip)

Log included with pw changed to xxxxxxxx. Note that in line 82, I added a note to show where the second attempt starts, due to the special char issue. I cannot see any obvious errors. There WERE shell errors---I had to change the shell script function names like upgrade-0.3-0.4 to upgrade0304, etc. No other modifications.

**Comment by kitefishlabs** [comment]
It seems to be requesting oauth.json?... and getting 404s over and over.

**Comment by lmarikannan** [comment]
@kitefishlabs CentOS related issues are fixed on this issue https://github.com/RestyaPlatform/board/issues/1609. It'll reflect on our future release. Or you can simply download dev branch restyaboard.sh file (https://raw.githubusercontent.com/RestyaPlatform/board/dev/restyaboard.sh) and execute again to install restyaboard.
