### ISSUE TITLE
Notification per board doesn't work since 0.6.1

### ISSUE THREAD

**Issue by bseclier** [RestyaPlatform/board#1560]
Hello,
I have an installation of restyaboard in the last version (0.6.1), since my upgrade, I can't see any notification per board.
In order to reproduce : when I click on the bell icon (bottom-right), I have 2 tabs : "All", which works fine and "In this board" which doesn't work : it loads 10 seconds and stop without anything displayed.

I'm I the only one here ? :)
Thanks,

Regards.

**Comment by lmarikannan** [comment]
@bseclier Sorry for that, now that issue is fixed on this commit https://github.com/RestyaPlatform/board/commit/a60653743575190e553422a7d8aebb515c06d834. You can update this file `{YOUR_SERVER}/server/php/R/r.php` by adding this `$construct_offset = '';` on this line https://github.com/RestyaPlatform/board/blob/dev/server/php/R/r.php#L1152  Or simply set debug_mode as `true` to `false` on this file `{YOUR_SERVER}/server/php/config.inc.php` (https://github.com/RestyaPlatform/board/blob/dev/server/php/config.inc.php#L15)

**Comment by bseclier** [comment]
Perfect, thank you for the very fast fix !
