### ISSUE TITLE
First comment disappear if two are posted

### ISSUE THREAD

**Issue by bseclier** [RestyaPlatform/board#1675]
Hello,
I can see a bug since I am in 6.2 :
When I insert a comment, everything works well. When I instantly add another comment (on the same card), the first is removed. We have to close and reopen the card in order to see them both.
Do you have this problem too ?

Thanks

**Comment by lmarikannan** [comment]
@bseclier Sorry for that, issue is confirmed and reproduced on our server also. After the fix, we're let you know.

**Comment by lmarikannan** [comment]
@bseclier Now the issue is fixed on this commit https://github.com/RestyaPlatform/board/commit/5eccb84c4ed51d043da1ac0a16f4834ba8ef763d. This will reflect on our future release, or you can simply remove this code from https://github.com/RestyaPlatform/board/commit/5eccb84c4ed51d043da1ac0a16f4834ba8ef763d#diff-9812550cecc4e99d42faa21f771c0b8cL3902 and replace on this place https://github.com/RestyaPlatform/board/commit/5eccb84c4ed51d043da1ac0a16f4834ba8ef763d#diff-9812550cecc4e99d42faa21f771c0b8cR3907
