### ISSUE TITLE
Default sort for cards doenst work

### ISSUE THREAD

**Issue by Yasharah** [RestyaPlatform/board#1738]
Hello,
i have a problem with the new default card sorting option.

## Expected Behavior
after i changed the Default sort for cards to "Created date" the sorting on the board should be like this all the time

## Current Behavior
the sorting works until i reload or reopen the page and reverts back to standard.

## Steps to Reproduce (for bugs)
1. change sorting
2. sorting works
3. press F5
4. sorting is back to the way it was before

**Comment by sridhar391** [comment]
@Yasharah Actually, we tried to reproduce the issue on our local server and we can't able to reproduce, and only the problem occurred in "Start date", now we fixed that issue in our `local commit`. Could you share screenshot or video for more details about that issue?

**Comment by Yasharah** [comment]
a video from the problem:

[bug-2018-04-12_11.00.45.mp4.zip](https://github.com/RestyaPlatform/board/files/1902216/bug-2018-04-12_11.00.45.mp4.zip)

as you can see the sorting is not saved after a reload of the page with F5. It is always back to the standard sorting.

**Comment by sridhar391** [comment]
@Yasharah we tried to reproduce the issue and added the video:
[reproduce_bug_12.04.2018.webm.zip](https://github.com/RestyaPlatform/board/files/1902990/reproduce_bug_12.04.2018.webm.zip)
we are unable to reproduce the issue. can you please share your team viewer details at info@restya.com, so that we can help you to solve the issue

**Comment by Yasharah** [comment]
the problem is fixed now. thanks again for your help!
