### ISSUE TITLE
Problem upgrading from 0.6.2 to latest version

### ISSUE THREAD

**Issue by Richigeht** [RestyaPlatform/board#2319]
## Expected Behavior

I expected that upgrading to the latest release would work and fix some of our issues indeed :)
## Current Behavior

I am not able to login while using the binaries of the new version, but if I switch back to the original ones, I am able to sign in just fine. 
I do get in my nginx logs: 
 pg_query_params(): Query failed: ERROR:  column &quot;is_login_failed&quot; of relation &quot;user_logins&quot; does not exist

If I run the upgrade script from 0.6.3 to 0.6.4 I get the following error:
INSERT INTO "acl_board_links_boards_user_roles" ("created", "modified", "acl_board_link_id", "board_user_role_id") VALUES
(now(), now(), (select id from acl_board_links where slug='archive_all_cards_in_the_list'), '1'),
(now(), now(), (select id from acl_board_links where slug='archive_all_cards_in_the_list'), '2');
psql:upgrade-0.6.3-0.6.4.sql:331: ERROR:  more than one row returned by a subquery used as an expression

All the other ones did run just fine. 

## Steps to Reproduce (for bugs)

1. I do start with 0.6.2
2. Run the SQL scripts
3. Copy over the new binaries into the existing folder.
4.

If I just download the latest version and just run that with my config file, after adding the permissions to the folders, I do get the following:
*760 FastCGI sent in stderr: "PHP message: PHP Notice:  Use of undefined constant CLIENT_INFORMATION - assumed 'CLIENT_INFORMATION' in /usr/share/nginx/html/restyaboard/server/php/bootstrap.php on line 46" while reading response header from upstream,

While not being able to successfully load/start the website. 
## Your Environment

* Version used: 0.6.2 and trying to upgrade to 0.6.6
* Environment name and version (e.g. OS, PHP, PostgreSQL): php7, postgreSQL 9.6, debian linux with nginx
* Operating System and version (desktop or mobile): Win 10, Chrome 72
* Link to your project:

**Comment by sridhar391** [comment]
@Richigeht please send us the `restyaboard_install.log` file if you have updated your Restyaboard using the install script `restyaboard.sh`  or 

If you have manually updated your Restyaboard, please tell us if you have downloaded the files from the latest release [Modern Talking version](https://github.com/RestyaPlatform/board/releases/download/v0.6.6/board-v0.6.6.zip) and executed the SQL files one by one in the below order in your Restyaboard Database
  - upgrade-0.6.2-0.6.3.sql
  - upgrade-0.6.3-0.6.4.sql
  - upgrade-0.6.5-0.6.6.sql

**Comment by Richigeht** [comment]
Hi
I did download them manually - thought require this for an upgrade and then executed the scripts one after another indeed :) 

Mit freundlichen Grüßen / Best regards 
Richi
Von meinem iPhone gesendet

**Comment by sridhar391** [comment]
@Richigeht please update your `config.inc.php` file of `v0.6.6` in `/usr/share/nginx/html/restyaboard/server/php` folder and the below error will be solved 

> If I just download the latest version and just run that with my config file, after adding the permissions to the folders, I do get the following:
*760 FastCGI sent in stderr: "PHP message: PHP Notice: Use of undefined constant CLIENT_INFORMATION - assumed 'CLIENT_INFORMATION' in /usr/share/nginx/html/restyaboard/server/php/bootstrap.php on line 46" while reading response header from upstream,

For the below error, it is ocuured because the `upgrade-0.6.3-0.6.4.sql` file has been executed more than once and it tell us that the datas are already been inserted in the table

> If I run the upgrade script from 0.6.3 to 0.6.4 I get the following error:
INSERT INTO "acl_board_links_boards_user_roles" ("created", "modified", "acl_board_link_id", "board_user_role_id") VALUES
(now(), now(), (select id from acl_board_links where slug='archive_all_cards_in_the_list'), '1'),
(now(), now(), (select id from acl_board_links where slug='archive_all_cards_in_the_list'), '2');
psql:upgrade-0.6.3-0.6.4.sql:331: ERROR: more than one row returned by a subquery used as an expression

For the below error, it will not occur, f you have run the `upgrade-0.6.5-0.6.6.sql` file in your Restyaboard Database

> pg_query_params(): Query failed: ERROR: column "is_login_failed" of relation "user_logins" does not exist

**Comment by Richigeht** [comment]
Shame on me! I was using the wrong postgreSQL instance hence it did not work and even though I did execute all of them, it of course did not work successfully. 
Works now fine - thanks for the quick responses!

**Comment by rrjanbiah** [comment]
@Richigeht Glad to know that you've got it work! Please feel free to open issues or contact us anytime.
