### ISSUE TITLE
Feature Request: Set card title image like Trello

### ISSUE THREAD

**Issue by CodexAnima** [RestyaPlatform/board#2608]
Hey there dear Restya team,

in Trello you can assign one of your attached image as card image header.

In Restyaboard v0.6.7 only the last attached file (not only images) is tried to use as card image header.

Can you implement a way of assigning card image headers like Trello?

Keep on rocking,
Matthias

**Comment by kaihelmarklein** [comment]
I miss that feature to very urgently.
It would be great to be possible to set an image as a cover for each card.
Regards, Kai

**Comment by rrjanbiah** [comment]
@kaihelmarklein 

Can you please share the use case here? That will help us to prioritize it

**Comment by kaihelmarklein** [comment]
We use Restya in our company.
In our sales team we organize many cards depending on the manufacturer.
The visual representation is important because it helps to keep the overview.
It is also more motivating than just text.
We link the cards with the logos of the respective manufacturers.
It must be ensured that the logos are not changed if you add another attachment.

**Comment by rrjanbiah** [comment]
@kaihelmarklein 

Thanks for your explanation.
