### ISSUE TITLE
Without page refresh, renaming checklist title leads to side effects

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#2622]
## Expected Behavior

Checklist title rename reflects immediately without any side effects

## Current Behavior

1. Renaming checklist also replaces card title (without refresh)
2. It removes checklist from card (till we refresh)

**Comment by sridhar391** [comment]
@rrjanbiah The issue has been fixed in the commit https://github.com/RestyaPlatform/board/pull/2625/commits/c9908c5310b5c1fe610cebd14fa60f50b67fa6fe

**Comment by morbificagent** [comment]
Hi there,

after a few Problems in the last weeks i cloned restya from

https://github.com/RestyaPlatform/board.git

And builded it with grunt.
Now i experienced the same Problem as described here.

I make changes in one cards checklist and my team-members see one of the checklist-points as card title in the next moment.
This is very confusing as this is marked as fixed in 0.6.8.

BTW i have strange session-problems too (#4073)  which are marked as fixed in a past version.

Not sure why these "old" problems are coming back to me as i am using the very newest version
