### ISSUE TITLE
non-working scripted installation

### ISSUE THREAD

**Issue by GrandpaGus** [RestyaPlatform/board#2727]
I may put in a install request, but posting this here as well because the default scripted install fails.

## Current Behavior

non-working installation. Shows apache2 default 'its working' webpage. nginx doesn't appear to want to start. 
accessing from intranet is requiring using ip to show webpage so local dns may be an issue (should/can I use ip during nginx setup instead of fqdn?)

## Environment
default ubuntu 18.x LTS desktop, using dhcp. 

## Process ##
Ubuntu LTS desktop install, all defaults plus extra apps/drivers checkbox.  dhcp. hostname restya.REMOVED.com
login as created user
open terminal
cd Downloads
wget https://raw.githubusercontent.com/RestyaPlatform/board/master/restyaboard.sh
chmod +x restyaboard.sh
sudo ./restyaboard.sh
   - accept all defaults and suggested paths.
   - Install all uninstalled software as prompted
   - do NOT enable ssl for public internet accessible install

[restyaboard_install.log](https://github.com/RestyaPlatform/board/files/3408065/restyaboard_install.log)

**Comment by sridhar391** [comment]
`non-working installation. Shows apache2 default 'its working' webpage. nginx doesn't appear to want to start.`

@GrandpaGus Please execute the command `service apache2 stop` to stop the apache server 

`accessing from intranet is requiring using ip to show webpage so local dns may be an issue (should/can I use ip during nginx setup instead of fqdn?)`

@GrandpaGus You can use your IP to setup the Restyaboard URL

**Comment by GrandpaGus** [comment]
after stopping apache2, now I don't get anything.. even when trying localhost.

**Comment by sridhar391** [comment]
@GrandpaGus Can you please mail us your convenient time for zoom screen share meeting at info@restya.com to solve the issue

**Comment by baskar383** [comment]
Due to inactivity.  we are closing this issue
