### ISSUE TITLE
Fresh install - Blank login screen - Ngix Logging going crazy!

### ISSUE THREAD

**Issue by johncarteroz** [RestyaPlatform/board#4023]
Bug/Issue
=======
I am not sure where the issue or bug lies but after a fresh install, the domain name (sanitized in my log file) simply goes to a white login screen (the url changes to: https://mydomain.com/#/users/login".

My general setup
=============
Centos 7
Ngix
Postgresql

Steps taken
=========
This is a fresh Centos install so no other packages will effect this install
1) Downloaded Restya
2) Used the SUPER EASY install script
3) I had DNS preconfigured but I did NOT have my SSL preconfigured. So the initial install had issues because NGIX would not start as the certificate file could not be located.
4) I used CERTBOT with the CERTONLY option then option 2 (creating a temporary webserver) to install the certificate.
5) After step 4, NGIX happily started
6) the /var/log/httpd/error.log file only had entries regarding missing missing certificate file... no errors after that.
7) when I went to the website either by public IP address or by domain name, it redirected to the login url but displayed a blank screen...
8) Even after blank screen loaded (using both FireFox & Safari) continued to log 3~4 entries in the access.log file. This continues unless the browser tab is closed or another url is entered.

I understand there is a free install service, but if there is an easy fix and if it can be published in case anyone else experiences the same issue, then I would prefer to publish that here.

I really thank you in advance for any help. I am really excited to get my hands on Restya. (I have been an avid Trello user for many years)

[restyaboard_install_sanitized.txt](https://github.com/RestyaPlatform/board/files/4460360/restyaboard_install_sanitized.txt)

**Comment by sridhar391** [comment]
@johncarteroz We have checked your Restyaboard installation log file and the the PostgreSQL installation failed, please install the PostgreSQL by executing the  below installation script by downloading the attached file and excuting the command `chmod +x postgresql_install.sh` and execute the command `./postgresql_install.sh`

We have seen that you tried to add the SSL certificate, Can you please tell us if your Restyaboard instance is publicly accessible or you have purchased the domain name, otherwise, please remove the below configurations from `/etc/nginx/conf.d/restyaboard.conf` file

    listen 443 ssl;

    ssl_certificate      /etc/letsencrypt/live/restya.com/fullchain.pem;
    ssl_certificate_key  /etc/letsencrypt/live/restya.com/privkey.pem;

    ssl_session_cache shared:SSL:1m;
    ssl_session_timeout  15m;

    # Set system wide SSL settings
    ssl_prefer_server_ciphers on;
    ssl_protocols TLSv1.2 TLSv1.1 TLSv1;

    #Forward Secrecy
    ssl_ciphers "EECDH+ECDSA+AESGCM EECDH+aRSA+AESGCM EECDH+ECDSA+SHA384 EECDH+ECDSA+SHA256 EECDH+aRSA+SHA384 EECDH+aRSA+SHA256 EECDH+aRSA+RC4 EECDH EDH+aRSA RC4 !aNULL !eNULL !LOW !3DES !MD5 !EXP !PSK !SRP !DSS";

    if ($scheme = 'http') {
        rewrite  ^/(.*)$  https://restya.com/$1 permanent;
    }

**Comment by shawncampbell** [comment]
I ran into a similar experience (i.e. blank white page, perpetual 404 AJAX requests for `api/v1/oauth.json`). In the end my issue was due to an nginx misconfiguration. Before running the Restyaboard install script, I configured the website and domain on the server. Consequently, after running the install script multiple nginx configurations existed for the same site/domain. To resolve the issue, I merged `/etc/nginx/conf.d/restyaboard.conf` and the pre-existing `/etc/nginx/sites-available/[existing config file]`. After restarting nginx, the login page loads as expected.
