### ISSUE TITLE
Configuration to run Restyaboard on a NGINX Reverse proxy

### ISSUE THREAD

**Issue by sridhar391** [RestyaPlatform/board#4166]
## Context
One of the users asked the configuration to run Restyaboard on a NGINX Reverse proxy

**Comment by monban** [comment]
The primary problem that you will run into with a reverse proxy is that you need to ensure the Host header gets passed through correctly, otherwise r.php will load 127.0.0.1 or something similar into the `$_server_domain_url` variable, which is used all over the place, perhaps most notably in the email templates. In order do do this in nginx your proxy_pass configuration should look something like:
```
location / {
    proxy_set_header Host $host;
    proxy_pass http://localhost:8000;
}
```
That will ensure the correct `$_SERVER['HTTP_HOST']` gets forwarded to the container / hidden vm. Possibly might be nice to make this configurable by environment variable? Something to consider.

**Comment by sridhar391** [comment]
@monban Thanks for your suggestion

**Comment by sridhar391** [comment]
We have added the documentation for configuring the Restyaboard on a NGINX Reverse proxy, please refer the link https://restya.com/board/docs/restyaboard-nginx-reverse-proxy-configuration/
