### ISSUE TITLE
No board in 'My Boards'

### ISSUE THREAD

**Issue by Aendrew87** [RestyaPlatform/board#585]
Yesterday I updated the r.php with the last version from the dev branch.
That was necessary to use the activation and password forgotten function.

Now there are no boards in 'My Boards'.
Then clicking 'Boards' and 'My Boards' on the bottom of the page all boards are listet.

Any ideas how to solve this?

**Comment by rrjanbiah** [comment]
@Aendrew87 Did you try to clear browser cache and or in incognito window?

**Comment by Aendrew87** [comment]
**@rrjanbiah** yes, i cleared the browser cache and there was no incognito window

**Comment by rrjanbiah** [comment]
@Aendrew87 What browser is that? Can you also try some other browser?

**Comment by Aendrew87** [comment]
i used several pcs and browsers.
there i used ie 11 and firefox 45.0.2.

This probleme started with the update of the r.php.

**Comment by ssivachidambaram** [comment]
Can you please update the changes mentioned in the below links instead of overwrite the r.php file? Because we have worked a lot in r.php for next version in dev branch.

Overwrite the r.php from master branch,
https://github.com/RestyaPlatform/board/blob/master/server/php/R/r.php

Then apply the changes only mentioned in the below link,
https://github.com/RestyaPlatform/board/pull/489/files

Then add only this line `'/users/forgotpassword'` as mentioned in this diff,
https://github.com/RestyaPlatform/board/pull/524/files#diff-9812550cecc4e99d42faa21f771c0b8cR4661

**Comment by Aendrew87** [comment]
**@ssivachidambaram** thanks a lot, now it is working - hope that there will be a new release soon.
