### ISSUE TITLE
When is restyaboard getting released in nodejs/ expressjs

### ISSUE THREAD

**Issue by rnjailamba** [RestyaPlatform/board#597]
http://imgur.com/fLHYSlG
![](http://imgur.com/fLHYSlG.jpg)

**Comment by rnjailamba** [comment]
Can i get access to this version if it is in progress

**Comment by rrjanbiah** [comment]
@rnjailamba We have only very early prototype version and that won't be usable for current version. Due to resource prioritization, we have reorganized ourselves and decided to focus PHP first till we ship all planned items. And so, we planned to revisit Node support little later.

As we have Swagger compliant API docs, in future we may use Swagger Codegen. If you want, you may start with editor.swagger.io using board.demo.restya.com/api_explorer/api.json
