### ISSUE TITLE
Persist card divider position in settings

### ISSUE THREAD

**Issue by rrjanbiah** [RestyaPlatform/board#683]
From @donat1 in forum https://groups.google.com/forum/#!topic/restya/-mYCBHtHeFs

Where do I have to change the frames within the card.

No the splitting seems to be 20/80 but I'd like to have 50/50 for the two columns.

Yes it persists, as long as I have opened the browser. But when I start again a browser, the preference is gone. Maybe I don't see a save button?

**Comment by lmarikannan** [comment]
Now the card divider position is stored in cookies. So the preference will persist while reopen browser (if the cookies are not deleted on close browser).

**Comment by lmarikannan** [comment]
Refer #714.

**Comment by CodexAnima** [comment]
Please reopen this issue/feature.

In v.0.6.7 you can drag the divider as desired. The new position state is saved as the user is logged in. if you close the browser (many of our users use the autoremove all cookies on closing browser), the divider position is reset to 50/50.

The divider position should be stored persistent (card level for global positioning? user level for custom positioning?)

So if an user logs in again the next day, the desired split view per card is restored again instead of resetted to 50/50.
