### ISSUE TITLE
Don`t work elastic search

### ISSUE THREAD

**Issue by iacsvrn** [RestyaPlatform/board#757]
Hello. I can`t find any text on board.

In settings, I set http://localhost:9200/ and "word" ( i.e.) as index.

But localhost isn`t lan ip of serv.

**Comment by rrjanbiah** [comment]
@iacsvrn Can you please attach your install log? Most probably, your ElasticSearch may not have properly installed or not started.

**Comment by lmarikannan** [comment]
@iacsvrn Were you able to find solution?

**Comment by iacsvrn** [comment]
[restyaboard_install.zip](https://github.com/RestyaPlatform/board/files/436475/restyaboard_install.zip)

**Comment by iacsvrn** [comment]
Any ideas, why it don`t work?

**Comment by lmarikannan** [comment]
@iacsvrn Sorry for delary.. 

> ++ echo 'GeoIP folder creation failed with error code 52'
> GeoIP folder creation failed with error code 52
> ++ exit 1

 We checked your restyaboard_install.log. It's related to https://github.com/RestyaPlatform/board/issues/703.

**Comment by iacsvrn** [comment]
Do you think, that search don`t workm because I don`t install?

So, if I had it already, I must remove it?

**Comment by rrjanbiah** [comment]
@iacsvrn Previously when GeoIP folder creation failed, we immediately exited with `exit 1`. And so, subsequent steps got completely ignored. 

So, if you use the install script where we have removed this `exit 1`, it will allow you to proceed to subsequent steps.

**Comment by lmarikannan** [comment]
@iacsvrn Were you able to find solution?

**Comment by lmarikannan** [comment]
@iacsvrn While check your log, ElasticSearch was installed but not started due to exit code. So can you please run the 5 commands line no. from `890` to `894` manually. Please refer, https://github.com/RestyaPlatform/board/blob/dc2b32f808e93201de2619a479d9aa0c63b522f8/restyaboard.sh#L890.

After started please execute this SQL query `UPDATE settings SET value = 0 WHERE name = 'elasticsearch.last_processed_activtiy_id';`

**Comment by lmarikannan** [comment]
Closing this for now. If you get any issues, please feel free to reopen.
